#!/bin/sh

rc=0
failed_tests=

test="$(dirname "$0")"
for file in $(
	find "${@:-"$test"}" -type f -name '*.sh' | grep -v '/lib.sh$'
)
do
	echo "$file"
	"$test"/littlecheck.py "$file"
	case $? in
		(0|125) ;;
		(*)
			rc=$?
			failed_tests="$failed_tests
$file"
			;;
	esac
done

if [ $rc -ne 0 ]; then
	echo "Failed tests:"
	echo "$failed_tests"
	exit 1
fi

exit $rc
