= Kakoune Language Server Protocol Client

Implemented in Rust.

== Installation

=== Pre-built binaries

==== MacOS

===== Homebrew

----
brew install ul/kak-lsp/kak-lsp
# enable service to not bother with manual start/restart
# note that you might want it w/o `sudo` despite of brew suggestion
# because some language servers are available only in user's PATH by default
brew services start ul/kak-lsp/kak-lsp
----

===== Manual

----
curl -O -L https://github.com/ul/kak-lsp/releases/download/v3.2.0/kak-lsp-v3.2.0-x86_64-apple-darwin.tar.gz
tar xzvf kak-lsp-v3.2.0-x86_64-apple-darwin.tar.gz

# replace `~/.local/bin/` with something on your `$PATH`
mv kak-lsp ~/.local/bin/

mkdir -p ~/.config/kak-lsp 
mv kak-lsp.toml ~/.config/kak-lsp/ 

# service for MacOS to not bother with manual start/restart
mv com.github.ul.kak-lsp.plist ~/Library/LaunchAgents/
launchctl load ~/Library/LaunchAgents/com.github.ul.kak-lsp.plist
----

==== Linux

----
wget https://github.com/ul/kak-lsp/releases/download/v3.2.0/kak-lsp.x86_64-unknown-linux-musl.tar.gz
tar xzvf kak-lsp.x86_64-unknown-linux-musl.tar.gz

# replace `~/.local/bin/` with something on your `$PATH`
mv kak-lsp ~/.local/bin/

mkdir -p ~/.config/kak-lsp 
mv kak-lsp.toml ~/.config/kak-lsp/ 
----

==== FreeBSD

----
wget https://github.com/ul/kak-lsp/releases/download/v3.2.0/kak-lsp-v3.2.0-x86_64-unknown-freebsd.tar.gz
tar xzvf kak-lsp-v3.2.0-x86_64-unknown-freebsd.tar.gz

# replace `~/.local/bin/` with something on your `$PATH`
mv kak-lsp ~/.local/bin/

mkdir -p ~/.config/kak-lsp 
mv kak-lsp.toml ~/.config/kak-lsp/ 
----

=== From the source

----
git clone https://github.com/ul/kak-lsp
cd kak-lsp

cargo build --release

# replace `~/.local/bin/` with something on your `$PATH`
ln -s $PWD/target/release/kak-lsp ~/.local/bin/

mkdir -p ~/.config/kak-lsp 
# or just link if you are okay with default config
cp kak-lsp.toml ~/.config/kak-lsp/

# service for MacOS to not bother with manual start/restart
ln -s $PWD/com.github.ul.kak-lsp.plist ~/Library/LaunchAgents/
launchctl load com.github.ul.kak-lsp.plist
----

== Language servers

`kak-lsp` doesn't manage installation of language servers, please install them by yourself for the languages you plan to use `kak-lsp` with. Please consult  https://github.com/ul/kak-lsp/wiki/How-to-install-servers[How to install servers] wiki page for quick installation of language servers supported by `kak-lsp` out of the box.

== Usage

`kak-lsp` is able to connect multiple editor sessions to multiple language servers. Therefore `kak-lsp` process should be started separately and having single one running is enough:

----
kak-lsp
----

Expect it to crash from time to time. Usually it's enough just to restart it. When you return to editing your files `kak-lsp` will restart language server. See Installation for example how to automate keeping `kak-lsp` alive under MacOS.

Now you have running kak-lsp service and need to make Kakoune aware of it.
To enable LSP support for configured languages (see the next section) just add following command to your `kakrc`:

----
%sh{kak-lsp --kakoune}
----

It will add completions, hover info and will bind goto definition to `gd`
(the latter is available as `:lsp-definition` command, feel free to bind it to any convenient key/alias or call directly).
References for a symbol under the main cursor are available via `:lsp-references` which is not bound to any key by default.
Rudimentary support for diagnostics is implemented as well.

== Configuration

kak-lsp is configured via configuration file in https://github.com/toml-lang/toml[TOML] format. By default kak-lsp tries to read `$HOME/.config/kak-lsp/kak-lsp.toml`, but you can override it with command-line option `--config`.

Look into the default `kak-lsp.toml` in the root of repository, it should be quite self-descriptive.

If you are setting any options via cli do not forget to append them to `%sh{kak-lsp --kakoune}` in your `kakrc`.
It's not needed if you change options in `~/.config/kak-lsp/kak-lsp.toml` file.

== Troubleshooting

If kak-lsp fails try to run it with `-vvv` command-line option to enable debug logging. If it will
not give enough insights to fix the problem or if the problem is a bug in kak-lsp itself please
don't hesitate to raise an issue.

== Versioning

kak-lsp follows https://semver.org/[SemVer] with one notable difference from common practice: we 
don't use 0 major version to indicate that product is not yet reached stability. Even for 
non-stable and not feature-complete product user should be clearly informed about breaking change. 
Therefore we start with major version 1 and increment it every time upgrade need user's attention.
