#!/bin/sh

set -eu

new=$1 # Pass the version numbers, like "1.2.3"

if ! git diff HEAD --quiet; then
	echo "$0: index and worktree must be clean"
	exit 1
fi

untracked=$(git ls-files --exclude-standard --others)
if [ -n "$untracked" ]; then
	echo "$0: must not have untracked files (cargo limitation), found: $untracked"
	exit 1
fi

old=$(git describe --tags | sed 's/^v//;s/-.*//')

if git tag | grep -qxF "v$new"; then
	echo "tag v$new already exists"
	exit 1
fi

set -x

sed -i "s/v$old/v$new/g" README.asciidoc
sed -i "0,/version/ s/$old-snapshot/$new/" Cargo.toml
sed -i "1s/Unreleased/$new - $(date --iso)/" CHANGELOG.md
cargo check # update Cargo.lock
git commit -am "v$new"
git tag "v$new" --message="$(ci/latest-changelog.sh)"
cargo publish

sed -i "0,/version/ s/$new/$new-snapshot/" Cargo.toml
cargo check # update Cargo.lock
sed -i 1i'## Unreleased\n' CHANGELOG.md
git commit -am 'start new cycle'

git push origin v$new

# Update homebrew package.

binary() {
	target_triple=$1
	url=https://github.com/kakoune-lsp/kakoune-lsp/releases/download
	url=$url/v$new/kakoune-lsp-v$new-$target_triple.tar.gz
	archive=${url##*/}
	while true
	do
		curl -O -L "$url"
		if file --brief --mime "$archive" | grep -q '^application/gzip;'; then
			break
		fi
		sleep 60
	done
	sha=$(sha256sum "$archive")
	sha=${sha%% *}
	rm "$archive"
	varname=$(echo "$target_triple" | tr - _)
	eval "${varname}_url=\$url"
	eval "${varname}_sha=\${sha%% *}"
}
binary aarch64-apple-darwin
binary x86_64-apple-darwin
binary x86_64-unknown-linux-musl
(
	cd ../homebrew-kakoune-lsp/
	cat >Formula/kakoune-lsp.rb <<- EOF
	# Automatically generated by ../kakoune-lsp/ci/$(basename "$0").sh
	class KakouneLsp < Formula
	  desc "Kakoune Language Server Protocol Client"
	  homepage "https://github.com/kakoune-lsp/kakoune-lsp/"
	  version "$new"

	  if Hardware::CPU.arm?
	    url "${aarch64_apple_darwin_url}"
	    sha256 "${aarch64_apple_darwin_sha}"
	  else
	    on_macos do
	      url "${x86_64_apple_darwin_url}"
	      sha256 "${x86_64_apple_darwin_sha}"
	    end
	    on_linux do
	      url "${x86_64_unknown_linux_musl_url}"
	      sha256 "${x86_64_unknown_linux_musl_sha}"
	    end
	  end

	  def install
	    bin.install "kak-lsp"
	  end

	  def caveats
	    <<~EOS
	      For usage instructions, see https://github.com/kakoune-lsp/kakoune-lsp/blob/v#{version}/README.asciidoc
	    EOS
	  end

	end
EOF
	git commit -am "v$new"
	git push origin HEAD:master
)

git push origin HEAD:master
